name: Scheduled Health Check

env:
  CLIENT_HEALTHCHECK_API_KEY: ${{ secrets.CLIENT_HEALTHCHECK_API_KEY }}

# Controls when the action will run.
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
